[package]
name = "vuln_collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
chrono = { version = "0.4.26", features = ["serde"] }
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"]}
serde_json = { version = "1.0.105", features = ["std"] }
tokio = { version = "1.32.0", features = ["full"] }
zip = "0.10.0-alpha.1"